#! /opt/iotuploader/bin/python3

import sys
sys.path.append("/opt/iotuploader/src/iot-uploader")
import json
from sqlalchemy import desc

from iotuploader.database import SessionLocal
from iotuploader.models import SensorData

db = SessionLocal()

def main():
    data = db.query(SensorData)\
            .order_by(desc(SensorData.id))\
            .limit(3)\
            .all()
    for d in data:
        print(json.dumps(d.to_dict(), indent=2))

if __name__ == "__main__":
    main()

